#pragma kernel ResetKernel
#pragma kernel StepKernel

Texture2D<float> readTex;
SamplerState sampler_readTex;

RWTexture2D<float> writeTex;
RWTexture2D<float4> outTex;

int rez;

[numthreads(1, 1, 1)]
void ResetKernel(uint3 id : SV_DispatchThreadID)
{
    writeTex[id.xy] = 0;
}

void Render(uint3 id, float state)
{
    outTex[id.xy] = state;
}

[numthreads(1, 1, 1)]
void StepKernel(uint3 id : SV_DispatchThreadID)
{
    writeTex[id.xy] = readTex[id.xy] + .1;
    Render(id, writeTex[id.xy]);
}
